controller_manager:
  ros__parameters:
    update_rate: 100 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint0_position_controller:
      type: position_controllers/JointGroupPositionController

    joint0_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    joint0_effort_controller:
      type: effort_controllers/JointGroupEffortController
    
    joint1_position_controller:
      type: position_controllers/JointGroupPositionController

    joint1_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    joint1_effort_controller:
      type: effort_controllers/JointGroupEffortController

    joint2_position_controller:
      type: position_controllers/JointGroupPositionController

    joint2_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    joint2_effort_controller:
      type: effort_controllers/JointGroupEffortController
    
    joint3_position_controller:
      type: position_controllers/JointGroupPositionController

    joint3_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    joint3_effort_controller:
      type: effort_controllers/JointGroupEffortController

    joint4_position_controller:
      type: position_controllers/JointGroupPositionController

    joint4_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    joint4_effort_controller:
      type: effort_controllers/JointGroupEffortController
    
    joint5_position_controller:
      type: position_controllers/JointGroupPositionController

    joint5_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    joint5_effort_controller:
      type: effort_controllers/JointGroupEffortController
    
    joint6_position_controller:
      type: position_controllers/JointGroupPositionController

    joint6_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    joint6_effort_controller:
      type: effort_controllers/JointGroupEffortController
    
    joint7_position_controller:
      type: position_controllers/JointGroupPositionController

    joint7_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    joint7_effort_controller:
      type: effort_controllers/JointGroupEffortController

    joint8_position_controller:
      type: position_controllers/JointGroupPositionController

    joint8_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    joint8_effort_controller:
      type: effort_controllers/JointGroupEffortController
    
    joint9_position_controller:
      type: position_controllers/JointGroupPositionController

    joint9_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    joint9_effort_controller:
      type: effort_controllers/JointGroupEffortController

    joint10_position_controller:
      type: position_controllers/JointGroupPositionController

    joint10_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    joint10_effort_controller:
      type: effort_controllers/JointGroupEffortController
    
    joint11_position_controller:
      type: position_controllers/JointGroupPositionController

    joint11_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    joint11_effort_controller:
      type: effort_controllers/JointGroupEffortController

    joint12_position_controller:
      type: position_controllers/JointGroupPositionController

    joint12_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    joint12_effort_controller:
      type: effort_controllers/JointGroupEffortController

    group_position_controller:
      type: position_controllers/JointGroupPositionController

    group_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    group_effort_controller:
      type: effort_controllers/JointGroupEffortController


joint0_position_controller:
  ros__parameters:
    joints:
      - FL0 rotational motor

joint0_velocity_controller:
  ros__parameters:
    joints:
      - FL0 rotational motor

joint0_effort_controller:
  ros__parameters:
    joints:
      - FL0 rotational motor

joint1_position_controller:
  ros__parameters:
    joints:
      - FL1 rotational motor

joint1_velocity_controller:
  ros__parameters:
    joints:
      - FL1 rotational motor

joint1_effort_controller:
  ros__parameters:
    joints:
      - FL1 rotational motor

joint2_position_controller:
  ros__parameters:
    joints:
      - FL2 rotational motor

joint2_velocity_controller:
  ros__parameters:
    joints:
      - FL2 rotational motor

joint2_effort_controller:
  ros__parameters:
    joints:
      - FL2 rotational motor

joint3_position_controller:
  ros__parameters:
    joints:
      - FR0 rotational motor

joint3_velocity_controller:
  ros__parameters:
    joints:
      - FR0 rotational motor

joint3_effort_controller:
  ros__parameters:
    joints:
      - FR0 rotational motor

joint4_position_controller:
  ros__parameters:
    joints:
      - FR1 rotational motor

joint4_velocity_controller:
  ros__parameters:
    joints:
      - FR1 rotational motor

joint4_effort_controller:
  ros__parameters:
    joints:
      - FR1 rotational motor

joint5_position_controller:
  ros__parameters:
    joints:
      - FR2 rotational motor

joint5_velocity_controller:
  ros__parameters:
    joints:
      - FR2 rotational motor

joint5_effort_controller:
  ros__parameters:
    joints:
      - FR2 rotational motor

joint6_position_controller:
  ros__parameters:
    joints:
      - BL0 rotational motor

joint6_velocity_controller:
  ros__parameters:
    joints:
      - BL0 rotational motor

joint6_effort_controller:
  ros__parameters:
    joints:
      - BL0 rotational motor

joint7_position_controller:
  ros__parameters:
    joints:
      - BL1 rotational motor

joint7_velocity_controller:
  ros__parameters:
    joints:
      - BL1 rotational motor

joint8_position_controller:
  ros__parameters:
    joints:
      - BL2 rotational motor

joint8_velocity_controller:
  ros__parameters:
    joints:
      - BL2 rotational motor

joint8_effort_controller:
  ros__parameters:
    joints:
      - BL2 rotational motor

joint9_position_controller:
  ros__parameters:
    joints:
      - BR0 rotational motor

joint9_velocity_controller:
  ros__parameters:
    joints:
      - BR0 rotational motor

joint9_effort_controller:
  ros__parameters:
    joints:
      - BR0 rotational motor

joint10_position_controller:
  ros__parameters:
    joints:
      - BR1 rotational motor

joint10_velocity_controller:
  ros__parameters:
    joints:
      - BR1 rotational motor

joint10_effort_controller:
  ros__parameters:
    joints:
      - BR1 rotational motor

joint11_position_controller:
  ros__parameters:
    joints:
      - BR2 rotational motor

joint11_velocity_controller:
  ros__parameters:
    joints:
      - BR2 rotational motor

joint11_effort_controller:
  ros__parameters:
    joints:
      - BR2 rotational motor









































group_position_controller:
  ros__parameters:
    joints:
      - BL0 rotational motor
      - BL1 rotational motor

group_velocity_controller:
  ros__parameters:
    joints:
      - BL0 rotational motor
      - BL1 rotational motor

group_effort_controller:
  ros__parameters:
    joints:
      - BL0 rotational motor
      - BL1 rotational motor
