general: 
  simu_or_real: true #fasle => real robot

motor_or_webots_config:
  robot_urdf: "singleleg.urdf"
  world: "singleleg.wbt"
  ros_control_config: "webot_singleleg_controller.yaml"
  number_of_motors: "2"  # 12 is the maximum number of motors
  joint0_controller: "joint0_velocity_controller"
  joint1_controller: "joint1_velocity_controller"



highcontroller: 

  
 